name: Gherkin

on:
  push:
    branches: ["Gherkin"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib && dotnet restore ./GherkinUnitTests/Unittestscoverage

      - name: Unittests build (creator @zaryanezrya)
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true
      
      - name: UnitTests run (creator @zaryanezrya)
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll
       
      - name: Gherkin Unittests build (creator @Tintanaa)
        run: dotnet build ./GherkinUnitTests/Unittestscoverage
      
      - name: Gherkin UnitTests run (creator @Tintanaa)
        run: dotnet test ./GherkinUnitTests/Unittestscoverage /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
