name: square equation test

on:
  push:
    branches: ["square_equation"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore SquareEquationLib && dotnet restore UnitTests

      - name: Test SquareEquation Build 1
        run: dotnet build SquareEquationLib --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test SquareEquation (creator @zaryanezrya)
        run: ./SquareEquationTest ./SquareEquationLib/bin/Debug/net7.0/SquareEquationLib.dll

      - name: Test SquareEquation Build 2
        run: dotnet build UnitTests

      - name: Test SquareEquation (creator @Tintanaa)
        run: dotnet test UnitTests /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
