name: Task7spaceship

on:
  push:
    branches: ["Task7spaceship"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./UARM_Flight && dotnet restore ./UnitTests

      - name: Test Build
        run: dotnet build ./UnitTests/XUnit.Coverage.sln --no-restore /p:ContinuousIntegrationBuild=true

      - name: MyTests
        run: dotnet test ./UnitTests /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov