name: SpaceBattle_Tests

on:
  push:
    branches: ["Task7spaceship"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore UARM_Flight && dotnet restore UARM_Flight_Test

      - name: Test Build
        run: dotnet build UARM_Flight_Test

      - name: MyTests
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov