name: SpaceBattle_Tests

on:
  push:
    branches: ["Task7/solution"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ConsoleApp1

      - name: Test Build
        run: dotnet build 

      - name: MyTests
        run: dotnet test UARM_Tests /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov